/* Code generated by RoboBlockly v1.3 */
#include <mindstorms.h>
CMindstorms robot;
double radius = 1.1;
double trackwidth = 4.54;

robot.driveDistance(5, radius);
robot.turnRight(90, radius, trackwidth);
robot.driveDistance(10, radius);
robot.turnRight(90, radius, trackwidth);
robot.driveDistance(5, radius);
robot.turnRight(90, radius, trackwidth);
robot.driveDistance(10, radius);
robot.turnRight(90, radius, trackwidth);
